- hosts: localhost
  pre_tasks:
    - name: Install xCode
      command: xcode-select --install
      ignore_errors: yes

    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      ignore_errors: yes

  tasks:
    - name: Install ZSH
      command: brew install zsh
      tags:
        - zsh

    - name: Make ZSH default shell
      shell: chsh -s /usr/local/bin/zsh
      tags:
        - zsh

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags:
        - zsh

    - name: Install ASDF
      command: brew install asdf
