- name: Installing stow
  community.general.homebrew:
    name: stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "https://github.com/raulfdm/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    version: main
    accept_hostkey: yes
  tags:
    - install
    - dotfiles
    - stow
